version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id. 
        columns:
          - name: date_date
            description: the date of purchase.

          - name: order_id
            description:  the id of the order.
          - name: product_id
            description: the id of the product.
          - name: revenue
            description: the revenue of the product.
          - name: quantity
            description: the quantity of the product.
        tests:
          - unique:
              column_name: "(orders_id||'-'||pdt_id)"
        

      - name: product
        identifier: raw_gz_product
        description: products of greenweez.
        columns:
          - name: products_id
            description: the id of the products.
            tests:
              - unique
              - not_null
              
              

          - name: purchase_price
            description: the purchase price of the products.


      - name: ship
        identifier: raw_gz_ship
        description: ships of greenweez
        columns:
          - name: orders_id
            description:  the order id for ships
            tests:
              - unique
              - not_null
                  
          - name: shipping_fee
            description:  the fees of the ships
          - name:  logcost
            description:  the logistic costs of ships
          - name: ship_cost
            description:  the ship costs
      - name: adwords
        identifier: raw_gz_adwords
        description: Contains information related to AdWords campaigns. Each row corresponds to a specific campaign and includes details such as clicks, date, impressions, ads cost, campaign name, campaign key, and paid source.
        columns:
          - name: click
            description: The number of clicks received by the campaign.
          - name: date_date
            description: The date of the campaign.
          - name: impression
            description: The number of impressions received by the campaign.
          - name: ads_cost
            description: The cost of the ads for the campaign.
          - name: camPGN_name
            description: The name of the campaign.
          - name: campaign_key
            description: The unique key identifying the campaign.
          - name: paid_source
            description: The source from which the campaign is paid.
      - name: bing
        identifier: raw_gz_bing
        description: The contains information related to shipping costs for orders. Each row corresponds to a specific order and includes details such as the order ID, shipping fee, logistics cost, and shipping cost.
        columns:
          - name: date_date
            description: The date of the order.
            tests:
              - not_null
          - name: paid_source
            description: The source from which the ad was paid for.
            tests:
              - not_null
          - name: campaign_key
            description: The key associated with the campaign.
            tests:
              - not_null
          - name: camPGN_name
            description: The name of the campaign.
            tests:
              - not_null
          - name: ads_cost
            description: The cost of ads associated with the order.
          - name: impression
            description: The number of impressions for the ad.
          - name: click
            description: The number of clicks on the ad.
      - name: criteo
        identifier: raw_gz_criteo
        description: The contains information related to shipping costs for orders. Each row corresponds to a specific order and includes details such as the order ID, shipping fee, logistics cost, and shipping cost.
        columns:
          - name: date_date
            description: The date of the order.
            tests:
              - not_null
          - name: paid_source
            description: The source from which the ad was paid for.
            tests:
              - not_null
          - name: campaign_key
            description: The key associated with the campaign.
            tests:
              - not_null
          - name: camPGN_name
            description: The name of the campaign.
            tests:
              - not_null
          - name: ads_cost
            description: The cost of ads associated with the order.
          - name: impression
            description: The number of impressions for the ad.
          - name: click
            description: The number of clicks on the ad.
      - name: facebook
        identifier: raw_gz_facebook
        description: The contains information related to shipping costs for orders. Each row corresponds to a specific order and includes details such as the order ID, shipping fee, logistics cost, and shipping cost.
        columns:
          - name: date_date
            description: The date of the order.
            tests:
              - not_null
          - name: paid_source
            description: The source from which the ad was paid for.
            tests:
              - not_null
          - name: campaign_key
            description: The key associated with the campaign.
            tests:
              - not_null
          - name: camPGN_name
            description: The name of the campaign.
            tests:
              - not_null
          - name: ads_cost
            description: The cost of ads associated with the order.
          - name: Impression
            description: The number of impressions for the ad.
          - name: click
            description: The number of clicks on the ad. 
models:
  - name: int_campaign
    description: data from all campaigns
    tests:
      - unique:
          column_name: "(campaign_key) || '-' || date_date)"
      - not_null:
          column_name: 
            - paid_source
            - campaign_name
  - name: int_campaign_days
    description: data from all campaigns based on day
    tests:
       - unique:
          column_name: date_date
  




    